##Condicionales.

Los condicionales son aquellos que usamos cuando queremos que el programa cheque una condición y haga o no haga algo al respecto después de verificarla. Por ejemplo:

In [1]:
if 0.0 == 0
    "El cero float es igual al cero int"
end

"El cero float es igual al cero int"

In [2]:
if 1 == 2
    "Algo no está bien"
else
    " 1 es distinto de 2"
end

" 1 es distinto de 2"

In [3]:
f(x) = x^2 -2x + 1
if f(1) < 10 
    #Podemos redefinir la función
    f(x) = x + 10
end
f(1)

11

Hasta ahora son cosas demasiado sencillas, pero se van a ir complicando. Además, puede checar multiples condiciones.

In [4]:
if 1 == 2
    "Nunca sucede esto"
elseif 1 == 3
    "tampoco sucede"
elseif 1 == 4
    "tampoco sucede"
else
    "no se cumplió ninguna condición"
end

"no se cumplió ninguna condición"

Además cada condicional puede verificar cosas como:
- $A = B$ y $B = C$ (se denota con && en Julia)
- $A = B$ o $B = C$ (se denota con || en Julia)

A continuacion unos ejemplos.

### &&

In [5]:
pi == π
pi

π = 3.1415926535897...

In [6]:
g(y) = sin(y)^2 + cos(y)^2

g (generic function with 1 method)

In [7]:
if g(pi) == 1.0 && g(2pi) == 1.0 #Se agrega el .0 para que lo identifique como Float
    println("Cumple ambas condiciones y su valor en π es: ", g(pi))
else
    println("No satisface las condiciones")
end
    

Cumple ambas condiciones y su valor en π es: 1.0


In [8]:
h(y) = exp(y)

h (generic function with 1 method)

In [9]:
if h(0) <= 1.0 && 1 == 2
    println("Cumple ambas condiciones")
else
    println("No satisface las condiciones")
end
    

No satisface las condiciones


Este tipos de condicionales pueden, entre muchas otras cosas, servir para checar intervalos "grandes". En la sección de bucles se explorará esto.

### ||

In [10]:
if sin(0) == 1 || sin(0) == 0
    "Se cumple una condición"
end

"Se cumple una condición"

In [11]:
if sin(0) == 0 || sin(0) == 1
    "Se cumple una condición"
end

"Se cumple una condición"

Pero, nuevamente hay que ser cuidadoso con las igualdades.

In [12]:
if sin(pi) == 0 || sin(pi) == 1
    "Se cumple una condición"
end

Resumiendo lo condicionales 

```if <condicion>
    <haz esto si la condicion inicial se cumple>
elseif <esta condicion o> || <esta otra condicion>
    <haz esto >
elseif <esta condicion y> && <y esta otra condicion>
    <haz esto >
else 
    <haz esto si no se satisface ninguna de las anteriores>
end
    ```
   

####¿Qué pasó aquí? Se debería cumplir al menos una igualdad ($\sin \pi = 0$) Calculemos 'sin(pi)'.

In [13]:
sin(pi)

1.2246467991473532e-16

Lo cual estrictamente no es cero, sino que es la aproximación de punto flotante que puede lograr la computadora. ¿Qué hacemos? La idea es darle un margen de error con un condicional doble, por ejemplo:

In [14]:
#Definimos una "tolerancia"
tolerancia = 1e-8

1.0e-8

In [15]:
if sin(pi) < 0 +tolerancia || sin(pi) < 0 - tolerancia
    "sin(pi) estás dentro del margen de tolerancia"
end

"sin(pi) estás dentro del margen de tolerancia"

## Rangos

Antes de empezar con los bucles veamos primero como generar rangos (los ejemplos de bucles con arreglos vendrán en 
la sección de arreglos. 

In [16]:
# Rango genérico de enteros.
rang_int = 0:10

0:10

In [17]:
# Rango con paso no entero
rang_noint = 0:1/pi:pi

0.0:0.3183098861837907:2.864788975654116

Verfiquemos algunos detalles de este segundo rango (es un poco más peculiar)

In [18]:
# Número de elementos
length(rang_noint)

10

In [19]:
# Primer y último elemento
rang_noint[1], rang_noint[end]

(0.0,2.864788975654116)

Por último, podemos generar rangos con el punto inicial, el punto final y el número de elementos que queremos, 
igualmente espaciados. 

In [20]:
rang_linsp = linspace(0, 2, 13)
rang_linsp[8]

1.1666666666666667

##Bucles 

Hay dos tipos de bucles 'for' y 'while'. Cada uno tiene su utilidades que quedarán claras en unos momentos.

Empecemos por el bucle 'for'. Este tipo de bucles se utiliza especificando el número de iteraciones que se desean, sin embargo, esto no es todo. Este tipo de bucle también puede correr en arreglos establecidos por el usuario, algo que en matemáticas pensariamos como:

$$ x^2 \ \forall \ x \  \in \ \mathbb{A}$$


donde $\mathbb{A}$ puede ser cualquier conjunto (usualmente especificado con rangos o arreglos).

Algo que no se explorará, pero vale la pena mencionar, es que los bucles 'for' pueden correr bajo dos variables en arreglos multidimensionales (teniendo un poco de cuidado).

In [21]:
nuevo_rang_noint = 0:pi/10:pi

0.0:0.3141592653589793:3.141592653589793

Notemos que no termina en $\pi$, ¿Por qué? Esto sucede cuando (rango[end] + el paso) > (último valor deseado) ¿Cómo se le hace para que termine en $\pi$? Lo que tenemos que hacer es dar un paso que permita llegar a $\pi$, debido a que éste se pasa.

## For
Ya sabemos usar rangos ahora utilicémoslos en un 'for'

In [22]:
# Sumemos los primeros 10 enteros, como todavía no sumamos ninguno ponemos nuestro valor inicial en 0
suma = 0
for i in 0:10 # tambien sirve i=0:10
    suma = suma + i
end
suma

55

In [23]:
# Comparemos con la suma de Gauss
suma == (10*11)/2

true

También podríamos haber usado el rango que ya habíamos creado (y lo haremos), pero le haremos una pequeña modificación.

In [24]:
nueva_suma = 0
for i in rang_int
    nueva_suma += i # se trata de notación para sumar a lo que ya se tenía
end
nueva_suma

55

Ahora, dejamos pendiente una utilidad del 'if' usando &&.

In [25]:
esta_en_el_intervarlo = true # Variable tipo 'bool' verdadero o falso
for i in nuevo_rang_noint
    if sin(i) >= 1 && sin(i) <= -1
        esta_en_el_intervarlo = false # con una vez que entre el condicional se vuelve falso
    end
end
esta_en_el_intervarlo

true

In [26]:
typeof(true)

Bool

##-- Ejercicio 1. Realicé un bucle 'for' que calcule el factorial de 10

##While 

El 'whilo' lo utilizamos para hacer un bucle que termine hasta satisfacer cierta condición. Hay que tener cuidado con el uso de 'whyle' porqué si le ponemos una condición que no se satisfaga nunca el programa no va a terminar. 


In [27]:
# Condiciones Iniciales
suma_whil = 0
i = 0 
while i <= 10
    suma_whil += i
    i += 1
end
suma_whil

55

In [28]:
j=0

while sin(j) < 0.5
    j += 1e-5
end
j, sin(j)

(0.5236000000002519,0.500001060362821)

##-- Ejercicio 2. Realicé un bucle 'while' que calcule el factorial de 10

## Tiempo de cálculo en la computadora

Tarde o temprano quizás querramos saber qué tanto tiempo tarda en correr nuestro programa o poder comparar dos pedazos de código que hacen lo mismo, para hacerlo tenemos convertir nuestro código en una función y usarla después de @time. Hay que correr esta celda dos veces porque la primera vez calcula el tiempo de compilación y ejecución, y la segunda vez solamente  calcula el tiempo de operación.

In [29]:
@time sin(90000000)

  0.000014 seconds (149 allocations: 10.167 KB)


-0.6924277025008503

## -- Ejercicio 3. Realicé funciones de los ejercicios anteriores y calcule el tiempo de cada uno.

##Vectores

Primero para definir vectores con componentes (x,y) simplemente tecleamos v = [x, y]. Si se tiene una pareja de vectores podemos operarlos con producto punto o cruz.

push, rands

In [30]:
v1 = [3,2]; v2 = [3 ,2]

2-element Array{Int64,1}:
 3
 2

In [31]:
#Primero probemos multiplicarlos
v1*v2

LoadError: LoadError: MethodError: `*` has no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
  *{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(!Matched::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{S,1},SubArray{S,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  *{TA,TB}(!Matched::Base.LinAlg.AbstractTriangular{TA,S<:AbstractArray{T,2}}, ::Union{DenseArray{TB,1},DenseArray{TB,2},SubArray{TB,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{TB,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  ...
while loading In[31], in expression starting on line 2

Lo cual era de esperarse porque los dos son vectores renglón. Para transponer un arreglo de una dimesión (o más) para el caso de un vector (o matríz) utulizamos "transpose(obejeo)" o "objeto'"

In [32]:
v1'*v2 #una manera de hacer producto punto

1-element Array{Int64,1}:
 13

In [33]:
dot(v1,v2)

13

In [34]:
#definos vectores con 3 componentes
u1 = [1,2,3]; u2 = [4,5,6]

3-element Array{Int64,1}:
 4
 5
 6

In [35]:
u3 = cross(u1,u2)

3-element Array{Int64,1}:
 -3
  6
 -3

In [36]:
dot(u1, u3) # efectivamente su producto punto es

0

##Matrices
Ahora veamos como definir matrices y algunas operaciones con matrices.

In [37]:
M1 = [1 2 3; 4 5 6; 7 8 9] ; M2 = [1 1 1; 2 2 2; 3 3 3]

3x3 Array{Int64,2}:
 1  1  1
 2  2  2
 3  3  3

In [38]:
M1*M2 == M2*M1

false

In [39]:
det(M1)

6.661338147750939e-16

In [40]:
eig(M1) # Eigenvalores y Eigenvectores

([16.116843969807043,-1.1168439698070427,-1.3036777264747022e-15],
3x3 Array{Float64,2}:
 -0.231971  -0.78583     0.408248
 -0.525322  -0.0867513  -0.816497
 -0.818673   0.612328    0.408248)

A veces cuando se trata de hacer matrices lo más conveniente es generar una matriz de ceros y luego modificarla.

In [41]:
Z = zeros(3, 3) # matriz de 3x3 de ceros

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [42]:
# modificando la matriz Z
Z[2,2] = 100
Z[2,3] = 20
Z[3,2] = 15
Z

3x3 Array{Float64,2}:
 0.0    0.0   0.0
 0.0  100.0  20.0
 0.0   15.0   0.0

In [43]:
# Supongamos que son la mente nos interesa una columna.
Z[1:end,2]

3-element Array{Float64,1}:
   0.0
 100.0
  15.0

In [44]:
# Digamos que queremos el cuadrado 2x2 de abajo a la derecha
Z[2:3,2:end]

2x2 Array{Float64,2}:
 100.0  20.0
  15.0   0.0

In [45]:
# también se pueden definr arreglos de más dimensiones
Z2 = zeros(3, 3, 3)
Z2[1, 1:3, 1:end] 

1x3x3 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0

## -- Ejercicio 4. Utilizando arreglos multidimensionales, bucles y condicionales genere una matriz de [Levi-Civita](https://en.m.wikipedia.org/wiki/Levi-Civita_symbol) de 3 dimensiones.

También se pueden generar matrices identidad matrices, de unos y matrices llenas de algún valor que deseemos.

In [46]:
# Identidad
eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [47]:
# Matrices de unos 
ones(3,3)

3x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [48]:
# Matrices de algún valor
fill(42, 3, 3)

3x3 Array{Int64,2}:
 42  42  42
 42  42  42
 42  42  42

Ahora veremos como hacer una matriz a partir de un arreglo unidimensional.

In [49]:
A = [i^2 for i in 1:8] # otra forma práctica de generar arreglos en un renglón

8-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36
 49
 64

In [50]:
reshape(A, 2, 4)

2x4 Array{Int64,2}:
 1   9  25  49
 4  16  36  64

Si estamos haciendo algo que no nos permite saber el tamaño del arreglo final podemos crear un arreglo vacío y rellenarlo.

In [51]:
Avac = []
# Rellenarlo de valores
for i in 1:5
    push!(Avac, rand())

end
Avac

5-element Array{Any,1}:
 0.26818  
 0.695521 
 0.369707 
 0.537874 
 0.0762382

In [52]:
Vvac = []
#Rellenarlo de vectores
for i in 1:5
    push!(Vvac, [rand(), rand()])
end
Vvac

5-element Array{Any,1}:
 [0.6874592879794643,0.5536321845993346] 
 [0.4912419875172884,0.31618799153146115]
 [0.12491485654952639,0.5032076253116096]
 [0.2519234130588184,0.43580675170156]   
 [0.7293412909721941,0.7364271918754592] 

## -- Ejercicio 5. Utilizando arreglos, bucles y números aleatorios genere una matriz de 0's y 1's de $10\times 6$. 

In [53]:
for i in 1:5
    println(rand([0,1]))
end

0
0
0
1
0


Por último, cuando queremos modificar un arreglo la forma típica de hacerlo es utilizando algún bucle y modificarlo elemento por elemento, sin emabargo, cuando se trata de una operación básica a todos los elementos del grupo se puede hacer de forma simplificada.

In [54]:
# Generemos un arreglo de prueba
Arr_pr = zeros(2,2)

2x2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [55]:
Arr_pr + ones(2,2) == Arr_pr + 1 

true

In [56]:
# otro arreglo de prueba
Arr_pr2 = [i^2 for i in 1:10]'

1x10 Array{Int64,2}:
 1  4  9  16  25  36  49  64  81  100

In [57]:
# ¿Podremos sacarla la raiz?
nuevo_arr = sqrt(Arr_pr2)

1x10 Array{Float64,2}:
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0

In [58]:
nuevo_arr^2

LoadError: LoadError: DimensionMismatch("A has dimensions (1,10) but B has dimensions (1,10)")
while loading In[58], in expression starting on line 1

Este ejercicio es sencillo y es fácil calcular el cuadrado de cada elemento usando un 'for', pero si el arreglo fuera de dos dimensiones tendríamos que usar dos 'for'. Esto se resuelve muy fácil, simplemente hay que especificar al operador que lo haga elemento por elemento agregando un '.' antes del operador.

In [59]:
nuevo_arr.^2

1x10 Array{Float64,2}:
 1.0  4.0  9.0  16.0  25.0  36.0  49.0  64.0  81.0  100.0